name: EDK2 Setup and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-edk2:
    runs-on: windows-2022
    
    steps:
    - name: Checkout EDK2 Setup Scripts
      uses: actions/checkout@v4
      with:
        path: edk2-setup-scripts
    
    - name: Checkout EDK2 Repository
      uses: actions/checkout@v4
      with:
        repository: tianocore/edk2
        path: edk2
        submodules: true
    
    - name: Copy Local ACPIPatcherPkg
      run: |
        echo "Copying local ACPIPatcherPkg to edk2 workspace..."
        Copy-Item -Path "edk2-setup-scripts/ACPIPatcherPkg" -Destination "edk2/ACPIPatcherPkg" -Recurse -Force
        echo "ACPIPatcherPkg copied successfully"
        if (Test-Path "edk2/ACPIPatcherPkg/ACPIPatcherPkg.dsc") {
          echo "SUCCESS: ACPIPatcherPkg.dsc found"
        } else {
          echo "WARNING: ACPIPatcherPkg.dsc not found"
          Get-ChildItem "edk2/ACPIPatcherPkg" -Recurse
        }
      shell: pwsh
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install EDK2 Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install edk2-pytool-library edk2-pytool-extensions regex
      shell: pwsh
    
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'
    
    - name: Install NASM
      run: |
        # Download and install NASM
        $nasmUrl = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip"
        $nasmZip = "$env:TEMP\nasm.zip"
        $nasmDir = "C:\NASM"
        
        Write-Host "Downloading NASM..."
        Invoke-WebRequest -Uri $nasmUrl -OutFile $nasmZip
        
        Write-Host "Extracting NASM..."
        Expand-Archive -Path $nasmZip -DestinationPath $env:TEMP
        
        Write-Host "Installing NASM to C:\NASM..."
        New-Item -ItemType Directory -Path $nasmDir -Force
        Copy-Item -Path "$env:TEMP\nasm-2.16.01\*" -Destination $nasmDir -Recurse -Force
        
        Write-Host "Adding NASM to PATH..."
        echo "C:\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
    
    - name: Build BaseTools
      run: |
        cd edk2
        echo "Setting up Visual Studio environment..."
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
        echo "Setting up Python environment..."
        where python
        set "PYTHON_COMMAND=python"
        python --version
        
        echo "Setting EDK2 environment variables..."
        set "WORKSPACE=%CD%"
        set "EDK_TOOLS_PATH=%CD%\BaseTools"
        set "BASE_TOOLS_PATH=%CD%\BaseTools"
        
        echo "Building BaseTools with Edk2ToolsBuild..."
        cd BaseTools
        python Edk2ToolsBuild.py
        
        if %ERRORLEVEL% neq 0 (
          echo "ERROR: BaseTools build failed"
          exit /b 1
        )
        
        echo "BaseTools build completed successfully"
        cd %WORKSPACE%
      shell: cmd
    
    - name: Build ACPIPatcherPkg
      run: |
        cd edk2
        echo "Setting up EDK2 environment..."
        call edksetup.bat
        
        echo "Verifying ACPIPatcherPkg is available..."
        if exist "ACPIPatcherPkg\ACPIPatcherPkg.dsc" (
          echo "SUCCESS: ACPIPatcherPkg.dsc found"
          echo "Building ACPIPatcherPkg..."
          build -a X64 -t VS2022 -p ACPIPatcherPkg/ACPIPatcherPkg.dsc
          echo "ACPIPatcherPkg build completed!"
        ) else (
          echo "ERROR: ACPIPatcherPkg.dsc not found!"
          dir ACPIPatcherPkg
          exit /b 1
        )
      shell: cmd
    
    - name: Upload Build Artifacts (if build successful)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: edk2-build-artifacts
        path: |
          edk2/Build/
          edk2/BaseTools/Bin/
        retention-days: 7
